config/routes.rb
Rails.application.routes.draw do
  resources :avatars
    devise_for :users, :controllers => { :registrations => "acme/registrations"}
    get '/annonces/moiobyavlenie' => 'annonces#mesannonces'
    get '/annonces/all', to:'annonces#index', as: 'vse_marshruti'
  resources :searches
  resources :annonces
  get '/vseuseri', to: 'vseuseri#index', as: 'vseuseri_path'
  get '/test', to: 'searches#searchall', as: 'searchall_path'
  get '/office', to: 'mymenu#index', as: 'mymenu_path'
  resources :conversations
  root to: 'searches#searchall'
  get '/conversations/:id/replay', to: 'conversations#replay', as: 'replay'
  post '/conversations/:id/replay', to: 'conversations#replay'

   get '/conversations/:id/replayForXs', to: 'conversations#replayForXs', as: 'replayForXs'
  post '/conversations/:id/replayForXs', to: 'conversations#replayForXs'

end

app/controllers/mymenu_controller.rb
class MymenuController < ApplicationController

	def index
		@avatar = Avatar.new
	end
end

app/helpers/mymenu_helper.rb
module MymenuHelper
end

app/views/mymenu/index.html.erb
<%= render 'shared/navbar'%>
 
<div class='container-fluid moyoffice'>
	<div class='row tekushiyprofil'>
		<div class='row text-center'>
			<p class='titlep'><%= current_user.prenom %>, добро пожаловать в офис</p></br>
		</div>
		<div class='col-md-2 user_avatar'>
			<%if current_user.avatars.first.present?%>
				<%= image_tag current_user.avatars.first.image.thumb('120x120#').url, class:'profile-picture'%>
			<%else%>
				<%= image_tag("no-profile.gif", class:'profile-picture')%>
			<%end%>
			<%if current_user.avatars.first.present?%>
				<%= form_for current_user.avatars.first do |f| %>
					  <div class="field">
					    <%= f.file_field :image, class:'hidden file_upload_btn'%>
					  </div>
					  <div class="actions">
					  	</br>
					    <%= button_tag(type: "submit", class: "poisk update_img hidden") do %>
					    	<p>Obnovit'</p>
					    <%end%>
					  </div>
				<% end %>
			<%else%>
				<%= form_for @avatar do |f| %>
					  <div class="field">
					    <%= f.file_field :image, class:'hidden file_upload_btn'%>
					  </div>
					  <div class="actions">
					  	</br>
					    <%= button_tag(type: "submit", class: "poisk update_img hidden") do %>
					    	<p>Obnovit'</p>
					    <%end%>
					  </div>
				<% end %>
			<%end%>
		</div>
		<div class='col-md-3'>
			<p>Имя: <%= current_user.prenom%><p>
			<%if current_user.voditel?%>
			<p>Обявление: <%= current_user.annonces.count%></p>
			<%end%>
		</div>
		<div class='col-md-4'>
			<p>Майл: <%= current_user.email%></p>
		</div>
	</div>
	<div class='row firstmenurow'>
		<%= link_to  edit_user_registration_path do%>
			<div class='col-md-6 text-left higlighted'>
				<div class='col-md-4'>
					<i class="fa fa-cogs" aria-hidden="true"></i>
				</div>
				<div class='col-md-8'>
					<h3>Настойки профиля</h3>
					<p>В настойках профиля можно добавить фотографию профиля, изменить или добавить персональные данные.</p>
				</div>
			</div>
		<%end%>

		<%if current_user.voditel?%>
           <%= link_to  annonces_moiobyavlenie_path do%>
				<div class='col-md-6 text-left higlighted mesannoncesbtn'>
					<div class='col-md-4 text-left'>
						<i class="fa fa-upload" aria-hidden="true"></i>
					</div>
					<div class='col-md-8'>
						<h3>Мои объявления</h3>
						<p>Нажав сюда, вы сможете посмотреть, обновить или удалить свои объявление.</p>
					</div>
				</div>
			<%end%>
		<%else%>
			<div class='col-md-6 text-left higlighted mesannoncesbtn'>
				<div class='col-md-4 text-left'>
					<i class="fa fa-upload" aria-hidden="true"></i>
				</div>
				<div class='col-md-8'>
					<h3>Мои объявления</h3>
					<p>Hа данный момент, y вас нет не одного объявления, нажмите на "создать объявления" чтоб апубликовать свое первое объявления.</p>
				</div>
			</div>
		<%end%>

	</div>
	<div class='row firstmenurow'>
		<%= link_to conversations_path(current_user) do%>
			<div class='col-md-6 text-left higlighted'>
				<div class='col-md-4 text-left'>
					<i class="fa fa-retweet" aria-hidden="true"></i>
				</div>
				<div class='col-md-8'>
					<h3>Mои сообщения</h3>
					<p>Все вашы переписки с водителями или с пасажирами сохранены в вашом почтовом яшике. Нажав сюда, вы сможите прочитать сообщения и ответить на них.</p>
				</div>
			</div>
		<%end%>
       <% if current_user.annonces.count < 4%>
        	<%= link_to  new_annonce_path do%>
				<div class='col-md-6 text-left higlighted'>
					<div class='col-md-4 text-left'>
						<i class="fa fa-plus" aria-hidden="true"></i>
					</div>
					<div class='col-md-8'>
						<h3>Создать объявления </h3>
						<p>На mymarshrut.com можно создать максимум 4 объявлений, если вы не достигли максимально дозволенного числа, вы можете создать новое объявление нажав сюда.</p>
					</div>
				</div>
			<%end%>
		<%else%>
			<div class='col-md-6 text-left higlighted'>
				<div class='col-md-4 text-left'>
					<i class="fa fa-plus" aria-hidden="true"></i>
				</div>
				<div class='col-md-8'>
					<h3>Создать объявления </h3>
					<p>Вы достигли максимально дозволенного числа объявлений. Пожалуйста обновите существующие или удалите чтоб создать новое.</p>
				</div>
			</div>
		<%end%>
	</div>
</div>

<%= render 'shared/footer'%>