config/routes.rb
Rails.application.routes.draw do
  resources :avatars
    devise_for :users, :controllers => { :registrations => "acme/registrations"}
    get '/annonces/moiobyavlenie' => 'annonces#mesannonces'
    get '/annonces/all', to:'annonces#index', as: 'vse_marshruti'
  resources :searches
  resources :annonces
  get '/vseuseri', to: 'vseuseri#index', as: 'vseuseri_path'
  get '/test', to: 'searches#searchall', as: 'searchall_path'
  get '/office', to: 'mymenu#index', as: 'mymenu_path'
  resources :conversations
  root to: 'searches#searchall'
  get '/conversations/:id/replay', to: 'conversations#replay', as: 'replay'
  post '/conversations/:id/replay', to: 'conversations#replay'

   get '/conversations/:id/replayForXs', to: 'conversations#replayForXs', as: 'replayForXs'
  post '/conversations/:id/replayForXs', to: 'conversations#replayForXs'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    before_action :set_conversation, only: [:replay, :show]

  def index
    @conversations = current_user.mailbox.conversations
  end
  
  def show 
    @conversation = current_user.mailbox.conversations.find(params[:id])
    @messages = @conversation.messages.order(created_at: :asc)

    respond_to do |format|
      format.html {render :layout => !request.xhr?}
    end
  end
  
  def new
    @recipients = User.all
  end
  
  def create
    recipient = User.find(params[:user_id])
    if params[:body] != nil
      receipt = current_user.send_message(recipient, params[:body], params[:subject])
      redirect_to conversations_path(receipt.conversation)
    else
      redirect_to(:back)
    end
  end

  def replay
    @conversation = current_user.mailbox.conversations.find(params[:id])
    @receipt = current_user.reply_to_conversation(@conversation, params[:body])
    respond_to do |format|
      format.html {render :layout => !request.xhr?}
      format.js
    end
  end

  def replayForXs
    @conversation = current_user.mailbox.conversations.find(params[:id])
    @receipt = current_user.reply_to_conversation(@conversation, params[:body])
    respond_to do |format|
      format.html {render :layout => !request.xhr?}
      format.js
    end
  end
  
  private
  def set_conversation
    @conversation = current_user.mailbox.conversations.find(params[:id])
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_show.html.erb
	<% @messages.each do |msg| %>
		<%msg.mark_as_read(current_user)%>
		<div class='row conversation-both text-right'>
			<div class='col-md-2'>
				<%if msg.sender == current_user%>
					<%if current_user.avatars.first.present?%>
						<img src='<%=current_user.avatars.first.image.thumb('55x55#').url%>' class='message-avatar'>
					<%else%>
						<img src='<%=asset_url("no-profile.gif")%>' class='message-avatar'>
					<%end%>
				<%else%>
					<%if msg.sender.avatars.first.present?%>
						<img src='<%=msg.sender.avatars.first.image.thumb('55x55#').url%>' class='message-avatar'>
					<%else%>
						<img src='<%= asset_url("no-profile.gif")%>' class='message-avatar'>
					<%end%>
				<%end%>
			</div>
			<div class='col-md-7 text-left'>
				<div class='speech-effect pinlineblock'>
					<%if msg.sender == current_user%>
						<div class='message-bubble'>
							<div class='pinlineblock speechbubble'>
							</div>
							<div class='pinlineblock msgmoi'>
								<p class='pinline'><%= msg.body%></p>
							</div>
						</div>
					<%else%>
						<div class='message-bubble2'>
							<div class='pinlineblock speechbubble2'>
							</div>
							<div class='pinlineblock msglui'>
								<p class='pinline'><%= msg.body%></p>
							</div>
						</div>
					<%end%>
				</div>
			</div>
			<div class='col-md-3'>

			</div>
			
		</div>
	<%end%>

app/views/conversations/index.html.erb
<body style='background-color:white'>
<%= render 'shared/navbar'%>
<div class='container-fluid messenger'>
	<div class='row mailboxheader text-center'>
		<div class='ribbon-vert-stitches-top'></div>
		<i class="pinline fa fa-inbox" aria-hidden="true"></i> &nbsp; &nbsp;<p class='pinline'> Мои сообщения</p>
		<div class='ribbon-vert-stitches-bottom'></div>
	</div>
	<div class='row all-individual-messages'>
		<div class='col-md-2 all-messages'>
			<ul class='liste-conversations'>
				<%@conversations.each do |conversation|%>
					<li data-convId = '<%= conversation.id%>' class="one-conversation msgsbackground">
						<div class='row enveloppe-messages text-left'>
							<div class='col-md-5 text-left avatar-container-md'>
								<%conversation.participants.each do |participant| %>
									<%if participant.prenom != current_user.prenom %>
										<%if participant.avatars.first.present?%>
											<img src='<%=participant.avatars.first.image.thumb('55x55#').url%>' class='message-avatar-md'>
										<%else%>
											<img src='<%= asset_url("no-profile.gif")%>' class='message-avatar-md'>
										<%end%>
									<%end%>
								<%end%> 
							</div>
							<div class='col-md-7 text-left'>
								<p class='nomdemessage'> 
									<%conversation.participants.each do |participant| %>
										<%if participant.prenom != current_user.prenom %>
										<%= participant.prenom%>
										<%end%>
									<%end%> 
								</p>
							</div>
						</div>
					</li>
				<%end%>
			</ul>
		</div>
		<div class='col-md-10 conv-past'>
			<div class='row messagesboxajax'>

			</div>
			<div class='row replayboxajax'>

			</div>
		</div>
	</div>
</div>
</body>

app/views/conversations/replay.html.erb
<div class='replaySlide'>
<%= form_tag replay_path(@conversation), method: :post, remote: true do%>
	<div class='row meesageinputplace'>
		<div class='col-md-10 message-area'>
			<%= text_area_tag :body, nil, class: 'messageinput'%>
		</div>
		<div class='col-md-2 send-btn-area text-center'>
			<%= button_tag(type:"submit", class:"btn-envoyer-message") do%>
				<i class="fa fa-paper-plane" aria-hidden="true"></i> <p class='pinline'> Отправить</p>
			<%end%>
		</div>
	</div>
<%end%>
</div>

app/views/conversations/replay.js.erb
$('.messageinput').val('');

var conversationId;
conversationId = $('.replaySlide').attr('data-convId');
	$.ajax('conversations/'+conversationId, {
		success: function(response){
			$('.conv-past .messagesboxajax').html(response).slideDown();
			$('.conversation-height').animate({scrollTop: $('.conversation-height').prop("scrollHeight")}, 0);
		}
	});

app/views/conversations/show.html.erb
<div class='conversation-height'>
	<%= render 'show'%>
</div>