config/routes.rb
Rails.application.routes.draw do
  resources :avatars
    devise_for :users, :controllers => { :registrations => "acme/registrations"}
    get '/annonces/moiobyavlenie' => 'annonces#mesannonces'
    get '/annonces/all', to:'annonces#index', as: 'vse_marshruti'
  resources :searches
  resources :annonces
  get '/vseuseri', to: 'vseuseri#index', as: 'vseuseri_path'
  get '/test', to: 'searches#searchall', as: 'searchall_path'
  get '/office', to: 'mymenu#index', as: 'mymenu_path'
  resources :conversations
  root to: 'searches#searchall'
  get '/conversations/:id/replay', to: 'conversations#replay', as: 'replay'
  post '/conversations/:id/replay', to: 'conversations#replay'

   get '/conversations/:id/replayForXs', to: 'conversations#replayForXs', as: 'replayForXs'
  post '/conversations/:id/replayForXs', to: 'conversations#replayForXs'

end

app/views/shared/_footer.html.erb
<div class='row footer-md'>
	<div class='col-md-3'>
		<div class='row text-center'>
			<div class='col-md-3 text-center'>
				<i class="fa fa-tag" aria-hidden="true"></i>
			</div>
			<div class='col-md-9 text-left'>
				<h5>Поиск маршрута</h5>
			</div>
		</div>
		<div class='row text-left'>
			<p>На сайте указано "Куда" и "Откуда", вам всего лишь нужно ввести название городов, чтобы найти нужный маршрут.</p>
		</div>
	</div>
	<div class='col-md-3'>
		<div class='row text-left'>
			<div class='col-md-3 text-left'>
				<i class="fa fa-thumbs-up" aria-hidden="true"></i>
			</div>
			<div class='col-md-9 text-left'>
				<h5>Создать объявление</h5>
			</div>
		</div>
		<div class='row text-left'>
			<%if user_signed_in?%>
				<p class='pinline'> Вы можете создать свое объявление нажав на  </p>
			<%= link_to new_annonce_path  do%>
				<p class='pinline'> <i class="glyphicon glyphicon-pencil"></i> cюда. </p></br>
			<%end%>
			<%else%>
				<p>Чтоб создать объявление нужно зарегистрироваться.</br> для этого нажмите <%=link_to 'сюда.', new_user_registration_path, class:'syudavert'%></i>
				</p>
			<%end%>
		</div>
	</div>
	<div class='col-md-3'>
		<div class='row text-center'>
			<div class='col-xs-3 text-center'>
				<i class="fa fa-check-square-o" aria-hidden="true"></i>
			</div>
			<div class='col-xs-9 text-left'>
				<h5>Зарегистрироваться</h5>
			</div>
		</div>
		<div class='row text-left'>
			<%if user_signed_in?%>
				<p> Вы можите отправить сообшение через наш сайт любому водителю. Для этого вам нужно нажать на объявление и написать сообшение, затем нажать на отправить.  
				</p></br>
			<%else%>
				<p>Чтобы связаться с водителем вам необходимо регистрироваться, для этого нажмите <%=link_to 'сюда.', new_user_registration_path%></p>
			<%end%>
		</div>
	</div>
	<div class='col-md-3'>
		<div class='col-md-6'>
			<ul>
				<h5>Про сайт</h5>
				<li><a href='#'>Кто мы?</a></li>
				<li><a href='#'>Что такое mymarshrut?</a></li>
				<li><a href='#'>Как им ползоваться?</a></li>
				<li><a href='http://mymarshrut.com/conditions.html'>Правила.</a></li>
				<li><a href='#'>Наши советы.</a></li>
			<ul>
		</div>
		<div class='col-md-6'>
			<ul>
				<h5>Контакт</h5>
				<li><a href='#'>Что мы могли бы улучшить?</a></li>
				<li><a href='#'>Сообщить нам о какой то дисфункции.</a></li>
				<li><a href='#'>Связаться с нами.</a></li>
			<ul>
		</div>
	</div>
	<div class='row copyright text-center'>
	</br>
		<p>Developed and designed by MYMARSHRUT</p>
		<p>©MYMARSHRUT 2016. All rights reserved. service@mymarshrut.com</p>
	</div>
</div>

app/views/shared/_navbar.html.erb
<%unless user_signed_in?%>
<nav class="navbar navbar-default navbar-static-top">
	<div class='container-fluid text-center'>
		<div class='navbar-brand'>
			<a href='<%=root_path%>'><i class="fa fa-bus" aria-hidden="true"></i></a>
		</div>
	<ul class='notconnectedlinks nav navbar-nav navbar-right hidden-xs'>
	<li><a href='<%= new_user_session_path%>'><i class="iconsignin fa fa-sign-in"></i>Bход </a></li>
	<li><a href='<%= new_user_registration_path%>'><i class="fa fa-pencil" aria-hidden="true"></i>Pегистрация</a></li>
	</ul>
	<ul class='notconnectedlinksmobile visible-xs'>
	<li><%= link_to new_user_session_path, class:'newusersessionclass' do%>
		<i class="iconsignin fa fa-sign-in"></i> Bход
		<%end%>
	</li>
	<li><%= link_to new_user_registration_path, class:'newusersessionclass' do%>
		<i class="fa fa-pencil" aria-hidden="true"></i> Pегистрация
		<%end%>
	</li>
	</ul>
	</div>
</nav>
<%else%>

<nav class="navbar navbar-default navbar-static-top">
	<div class='container-fluid text-center padding'>
		<div class='navbar-header'>
			<div class='navbar-brand'>
			<a href='<%=root_path%>'><i class="fa fa-bus" aria-hidden="true"></i></a>
		</div>
				<% if current_user.mailbox.conversations.unread(current_user).count == 0 %>
					<button type'button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
						<span class='sr-only'>navigateur</span>
						<span class='icon-bar'></span>
						<span class='icon-bar'></span>
						<span class='icon-bar'></span>
					</button>
				<%else%>
					<button type'button' class='notibtn navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
						<div>
						<span class='sr-only'>navigateur</span>
						<p class='notif'><i class="fa fa-bell" aria-hidden="true"></i> <%=current_user.mailbox.conversations.unread(current_user).count%></p>
						</div>
					</button>
				<%end%>
		</div>
			<div class='col-md-10 col-md-offset-1 padding'>
		<ul class='notconnectedlinks nav navbar-nav navbar-right collapse navbar-collapse text-left'>
			<li> <%= link_to mymenu_path_url do%>
				<div class='pinlineblock'>
					<%if current_user.avatars.first != nil %>
						<%= image_tag current_user.avatars.first.image.thumb('50x50#').url, class:'profile-picturenav'%>
					<%else%>
						<%= image_tag("no-profile.gif", class:'profile-picturenav')%>
					<%end%>
				</div> Мой офис
				<%end%>
			</li>
			<% if current_user.mailbox.conversations.unread(current_user).count == 0 %>
			<li><%= link_to conversations_path(current_user) do%>
			<i class="glyphicon glyphicon-envelope"></i> Мои сообщения
			<%end%>
			</li>
			<%else%>
			<li>
			<%= link_to conversations_path(current_user) do%>
			<p class='notif'><i class="glyphicon glyphicon-envelope"></i> <%=current_user.mailbox.conversations.unread(current_user).count%> сообщение</p>
			<%end%>
			</li>
			<%end%>
            	<li role="separator" class="divider"></li>
            <li><%= link_to destroy_user_session_path, :method => :delete do%>
				<i class='glyphicon glyphicon-off'></i> Выход 
				<%end%>
			</li>
		</ul>
	</div>
	</div>
</nav>
<%end%>