config/routes.rb
Rails.application.routes.draw do
  resources :avatars
    devise_for :users, :controllers => { :registrations => "acme/registrations"}
    get '/annonces/moiobyavlenie' => 'annonces#mesannonces'
    get '/annonces/all', to:'annonces#index', as: 'vse_marshruti'
  resources :searches
  resources :annonces
  get '/vseuseri', to: 'vseuseri#index', as: 'vseuseri_path'
  get '/test', to: 'searches#searchall', as: 'searchall_path'
  get '/office', to: 'mymenu#index', as: 'mymenu_path'
  resources :conversations
  root to: 'searches#searchall'
  get '/conversations/:id/replay', to: 'conversations#replay', as: 'replay'
  post '/conversations/:id/replay', to: 'conversations#replay'

   get '/conversations/:id/replayForXs', to: 'conversations#replayForXs', as: 'replayForXs'
  post '/conversations/:id/replayForXs', to: 'conversations#replayForXs'

end

app/models/annonce.rb
class Annonce < ActiveRecord::Base
  dragonfly_accessor :image
    dragonfly_accessor :image2
      dragonfly_accessor :image3
  belongs_to :user
  validates_associated :user, :message => "Вы неможите создавать болче чем 4 объявление."
  validates_presence_of :ville_depart, :message => "Вы не указали откуда вы едите!"
  validates_presence_of :ville_arrive, :message => "Вы не указали куда вы едите!"
  validates_presence_of :date_depart, :message => "Вы не указали когда вы едите!"
  validates_presence_of :prix_passager, :message => "Вы не указали цену за проезд!"
end

app/controllers/annonces_controller.rb
class AnnoncesController < ApplicationController
  before_action :set_annonce, only: [:show, :edit, :update, :destroy]

  # GET /annonces
  # GET /annonces.json
  def index
    if current_user.email == "nohchi.eu@gmail.com"
    @annonces = Annonce.all
    else 
    redirect_to root_path, notice: 'Vam nelzya na etu stranicu'
    end
  end

  
  # GET /annonces/1
  # GET /annonces/1.json
  def show
  end

  # GET /annonces/new
  def new
    if user_signed_in?
      @annonce = Annonce.new
    else
      redirect_to new_user_session_path, notice: 'Для того чтобы создать объявление необходимо зарегистрироваться'
    end
  end

  # GET /annonces/1/edit
  def edit
  end

  # POST /annonces
  # POST /annonces.json
  def create
    @annonce = current_user.annonces.build(annonce_params)

    respond_to do |format|
      if @annonce.save
        format.html { redirect_to root_path :flash => {:notice => "объявление создано" }}
        format.json { render :show, status: :created, location: @annonce }
      else
        format.html { render :new }
        format.json { render json: @annonce.errors, status: :unprocessable_entity }
      end
    end
  end

  def mesannonces
    @mesannonces = Kaminari.paginate_array(current_user.annonces).page(params[:page]).per(6)
  end
  # PATCH/PUT /annonces/1
  # PATCH/PUT /annonces/1.json
  def update
    respond_to do |format|
      if @annonce.update(annonce_params)
        format.html { redirect_to @annonce,:flash => { :notice => "объявление обновлен" } }
        format.json { render :show, status: :ok, location: @annonce }
      else
        format.html { render :edit }
        format.json { render json: @annonce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annonces/1
  # DELETE /annonces/1.json
  def destroy
    @annonce.destroy
    respond_to do |format|
      format.html { redirect_to annonces_moiobyavlenie_path, notice: 'объявление удалено' }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_annonce
      @annonce = Annonce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def annonce_params
      params.require(:annonce).permit(:ville_depart, :ville_arrive, :date_depart, :nombre_chauffeurs, :nombre_place, :telephones, :marque_vehicule, :annee_vehicule, :prix_passager, :poid_max_passager, :accept_colis, :accept_colis_valeur, :prix_kg_colis, :poid_max_colis, :poid_min_colis, :arrets_chaque, :description, :image, :image2, :image3, :villeinter1, :villeinter2, :villeinter3, :villeinter4, :villeinter5, :villeinter6, :villeinter7, :villeinter8, :villeinter9, :villeinter10, :telephones2, :telephones3, :telephones4, :telephones5, :telephones_type1, :telephones_type2, :telephones_type3, :telephones_type4, :telephones_type5, :telephone_type1, :telephone_type2, :telephone_type3, :telephone_type4, :wifi, :chay)
    end
    
    
end

app/helpers/annonces_helper.rb
module AnnoncesHelper
end

app/views/annonces/edit.html.erb
<%= render 'shared/navbar' %>


<body style='background-color:white'>
	<div class='ribbon-vert'>
		<div class='ribbon-vert-stitches-top'></div>
		<div class='row ribbon-vert-content'><h1>
			<div class='row text-center'>
					Редактировать / Обновить объявление
			</div>
		</h1></div>
		<div class='row ribbon-vert-stitches-bottom'></div>
	</div>
	<div class='container-fluid listing'>
	<%= render 'form' %>
	</div>
	</br>
	</br>
</body>

app/views/annonces/index.html.erb
	<body class='annoncesindex'>	
		<%= render 'shared/navbar' %>

<ul>
<% @annonces.each do |annonce| %>
<li><h3>annonce id: <%= annonce.id %>, user mobile: <%= annonce.user.mobile_number%>, annonce telephone:<%= annonce.telephones%>.</h3></li>
<%end%>
</ul>

app/views/annonces/mesannonces.html.erb
<%= render 'shared/navbar' %>
<%@mesannonces.each do |annonce|%>	
	<div class='container-fluid mesannoncesback mesannon text-center'>
		<div class='row text-left '>
			<div class='col-md-3 editmenu'>
				<p class='pinline'><i class="fa fa-pencil" aria-hidden="true"></i> <%= link_to 'Обновить', edit_annonce_path(annonce), class:'tabulation' %></p><div class='tabulation pinline'></div>
				<p class='pinline'><i class="fa fa-trash" aria-hidden="true"></i> <%= link_to 'Удалить ', annonce, :method => :delete, confirm: "Вы уверены что хотите удалить объявление?"%></p>
			</div>
		</div>
		<div class='thebackground'>
		<div class='row ligne text-left'>
			<div class=' col-md-4 photo'>
				<%= content_tag(:div, content_tag(:p, "ВОДИТЕЛЬ УЕХАЛ"), class: "expired") if annonce.date_depart < Date.today %>
				<%if annonce.image_stored?%>
					<%= image_tag annonce.image.thumb('300x250#').url%>
				<%else%>
					<div class='fotonotfound'>
					</div>
				<%end%>
			</div>
			<div class='col-md-8 text-left informaciii'>
				<div class='row'>		
					<div class= 'col-md-8 text-center datedirection'>
						<p> <%= annonce.ville_depart.truncate_words(1, omission: ' ') %>
						<%if annonce.villeinter1?%>
							<%unless annonce.villeinter2?%>
								<i class="fa fa-angle-right"aria-hidden="true"></i>
								<%=annonce.villeinter1.truncate_words(1, omission: ' ') %>
							<%end%>
						<%end%>
						<i class="fa fa-angle-right"aria-hidden="true"></i>
						<%= annonce.ville_arrive.truncate_words(1, omission: ' ')%></p>
					</div>
					<div class= 'col-md-4 text-right prix'>
						<h3><%= annonce.prix_passager%><i class='fa fa-eur'></i></h3>
						<h5 class='ladate'><%= annonce.date_depart.strftime("%d/%m/%Y") %></h5>
					</div></br>
				</div>
				<div class='row infodumilieu'>
					<div class='col-md-4 listing-information'>
						<%if annonce.nombre_chauffeurs?%>
							<% if annonce.nombre_chauffeurs == 1%>
								<p><i class='fa fa-male'> </i>   <%= annonce.nombre_chauffeurs %> Водитель</p>
							<%else%>
								<p><i class='fa fa-users'> </i>   <%= annonce.nombre_chauffeurs %> Водителя</p>
							<%end%>
						<%else%>
							<p><i class='fa fa-male'> </i> 1 Водитель</p>
						<%end%>
						<%if annonce.poid_max_passager?%>
							<p><i class='fa fa-suitcase'></i>   <%= annonce.poid_max_passager %> кг/макс</p> 
						<%else%>
							<p><i class='fa fa-suitcase'></i> Вес багажа --</p>
						<%end%>
						<%if annonce.arrets_chaque?%>
							<% if annonce.arrets_chaque == 1%>
								<p><i class='fa fa-coffee'></i> Остановка каждый час</p>
							<%elsif annonce.arrets_chaque == 2 || 3%>
								<p><i class='fa fa-coffee'></i> Остановка каждые <%= annonce.arrets_chaque %> часа</p>
							<%elsif annonce.arrets_chaque == 4%>
								<p><i class='fa fa-coffee'></i> остановка каждые <%= annonce.arrets_chaque %> часа</p>
							<%elsif annonce.arrets_chaque > 4%>
								<p><i class='fa fa-coffee'></i> Остановка каждые <%= annonce.arrets_chaque %> часов</p>
							<%end%>	

						<%else%>
							<p><i class='fa fa-coffee'></i> Остановки по усмотрению водителя</p>
						<%end%>
					</div>
					<div class='col-md-4 annonce_info2 listing-information'>
						<% if annonce.accept_colis == true%>
							<p><i class='fa fa-check-circle'> </i> Перевозка груза:</p>
							<p> <%= annonce.prix_kg_colis%> <i class='fa fa-eur'> </i> кг. мин вес  <%= annonce.poid_min_colis%> кг</p>
						<%else%>
							<p><i class='fa fa-times-circle'> </i> Перевозка посылок</p>
						<%end%>
						<% if annonce.accept_colis_valeur == true%>
							<p><i class='fa fa-check-circle'> </i> Перевозка ценных бумаг</p>
						<%else%>
							<p><i class='fa fa-times-circle'> </i> Перевозка ценных бумаг</p>
						<%end%>
					</div>
					<div class='col-md-4 text-left prixcontact listing-information'>
						<%if annonce.telephones?%>
							<%if annonce.telephones_type1?%>
								<p class='pinline'><i class="fa fa-whatsapp" aria-hidden="true"></i> </p>
							<%end%>
							<%if annonce.telephone_type1?%>
								<p class='pinline'><i class="fa fa-mobile" aria-hidden="true"></i> </p>
							<%end%>
							<p class='pinline'><%=annonce.telephones%></p></br>
						<%end%>

						<%if annonce.telephones2?%>
							<%if annonce.telephones_type2?%>
								<p class='pinline'><i class="fa fa-whatsapp" aria-hidden="true"></i> </p>
							<%end%>
							<%if annonce.telephone_type2?%>
								<p class='pinline'><i class="fa fa-mobile" aria-hidden="true"></i> </p>
							<%end%>
							<p class='pinline'><%=annonce.telephones2%></p></br>
						<%end%>

						<%if annonce.telephones3?%>
							<%if annonce.telephones_type3?%>
								<p class='pinline'><i class="fa fa-whatsapp" aria-hidden="true"></i> </p>
							<%end%>
							<%if annonce.telephone_type3?%>
								<p class='pinline'><i class="fa fa-mobile" aria-hidden="true"></i> </p>
							<%end%>
							<p class='pinline'><%=annonce.telephones3%></p></br>
						<%end%>

						<%if annonce.telephones4?%>
							<%if annonce.telephones_type4?%>
								<p class='pinline'><i class="fa fa-whatsapp" aria-hidden="true"></i> </p>
							<%end%>
							<%if annonce.telephone_type4?%>
								<p class='pinline'><i class="fa fa-mobile" aria-hidden="true"></i> </p>
							<%end%>
							<p class='pinline'><%=annonce.telephones4%></p>
						<%end%>
					</div>
				</div>
			</div>
		</div>
		<%if annonce.villeinter2?%>
		<div class='row marshrut'>
			<div class='row text-center map'>
					<div class='pinlineblock gorod'>
						<div class='entourp'>
						<p class='pinline'><%= annonce.ville_depart.truncate_words(1, omission: ' ') %></p>
						</div>
						</br>
						<h3 class='pinline spec'><i class="fa fa-circle-o" aria-hidden="true"></i><div class='maplinespec pinline'></div>
						</h3>
					</div>
					<%if annonce.villeinter1?%>
						<div class='pinlineblock gorod'>
							<div class='entourp'>
								<p class='pinline'><%=annonce.villeinter1.truncate_words(1, omission: ' ') %></p>
							</div>
							</br>
							<h4 class='pinline'><i class="fa fa-circle" aria-hidden="true"></i>
							<div class='mapline pinline'></div></h4>
						</div>
					<%end%>
					<%if annonce.villeinter2?%>
						<div class='pinlineblock gorod'>
							<div class='entourp'>
								<p class='pinline'><%=annonce.villeinter2.truncate_words(1, omission: ' ') %></p>
							</div>
							</br>
							<h4 class='pinline'><i class="fa fa-circle" aria-hidden="true"></i>
							<div class='mapline pinline'></div></h4>
						</div>
					<%end%>
					<% if annonce.villeinter3?%>
						<div class='pinlineblock gorod'>
							<div class='entourp'>
								<p class='pinline'><%=annonce.villeinter3.truncate_words(1, omission: ' ') %></p>
							</div>
							</br>
							<h4 class='pinline'><i class="fa fa-circle" aria-hidden="true"></i>
							<div class='mapline pinline'></div></h4>
						</div>
					<%end%>
					<% if annonce.villeinter4?%>
						<div class='pinlineblock gorod'>
							<div class='entourp'>
								<p class='pinline'><%=annonce.villeinter4.truncate_words(1, omission: ' ') %></p>
							</div>
							</br>
							<h4 class='pinline'><i class="fa fa-circle" aria-hidden="true"></i>
								<div class='mapline pinline'></div></h4>
						</div>
					<%end%>
					<% if annonce.villeinter5?%>
						<div class='pinlineblock gorod'>
							<div class='entourp'>
								<p class='pinline'><%=annonce.villeinter5.truncate_words(1, omission: ' ') %></p>
							</div>
							</br>
							<h4 class='pinline'><i class="fa fa-circle" aria-hidden="true"></i>
							<div class='mapline pinline'></div></h4>
						</div>
					<%end%>
					<% if annonce.villeinter6?%>
						<div class='pinlineblock gorod'>
							<div class='entourp'>
								<p class='pinline'><%=annonce.villeinter6.truncate_words(1, omission: ' ') %></p>
							</div>
							</br>
							<h4 class='pinline'><i class="fa fa-circle" aria-hidden="true"></i>
								<div class='mapline pinline'></div></h4>
						</div>
					<%end%>
					<% if annonce.villeinter7?%>
						<div class='pinlineblock gorod'>
							<div class='entourp'>
								<p class='pinline'><%=annonce.villeinter7.truncate_words(1, omission: ' ') %></p>
							</div>
							</br>
							<h4 class='pinline'><i class="fa fa-circle" aria-hidden="true"></i>
								<div class='mapline pinline'></div></h4>
						</div> 
					<%end%>
					<% if annonce.villeinter8?%>
						<div class='pinlineblock gorod'>
							<div class='entourp'>
								<p class='pinline'><%=annonce.villeinter8.truncate_words(1, omission: ' ') %></p>
							</div>
							</br>
							<h4 class='pinline'><i class="fa fa-circle" aria-hidden="true"></i>
								<div class='mapline pinline'></div></h4>
						</div>
					<%end%>
					<% if annonce.villeinter9?%>
						<div class='pinlineblock gorod'>
							<div class='entourp'>
								<p class='pinline'><%=annonce.villeinter9.truncate_words(1, omission: ' ') %></p>
							</div>
							</br>
							<h4 class='pinline'><i class="fa fa-circle" aria-hidden="true"></i>
								<div class='mapline pinline'></div></h4>
						</div>
					<%end%>
					<% if annonce.villeinter10?%>
						<div class='pinlineblock gorod'>
							<div class='entourp'>
								<p class='pinline'><%=annonce.villeinter10.truncate_words(1, omission: ' ') %></p>
							</div>
							</br>
							<h4 class='pinline'><i class="fa fa-circle" aria-hidden="true"></i>
							<div class='mapline pinline'></div></h4>
						</div>
					<%end%>

					<div class='pinlineblock gorod'>
						<div class='entourp'>
								<p class='pinline'><%=annonce.ville_arrive.truncate_words(1, omission: ' ') %></p>
							</div>
						</br>
						<h3 class='pinline spec'><i class="fa fa-circle-o" aria-hidden="true"></i></h3>
					</div>
			</div>

		</div>
		<%end%>
		</div>
	</div>
<%end%>
<div class='container-fluid text-center'>
	<%= paginate @mesannonces%>
</div>
<%= render 'shared/footer'%>

app/views/annonces/new.html.erb
<%= render 'shared/navbar' %>


<body style='background-color:white'>
</br>
	<div class='ribbon-vert'>
		<div class='ribbon-vert-stitches-top'></div>
		<div class='row ribbon-vert-content'><h1>
			<div class='row text-center'>
					Создать Объявление 
			</div>
		</h1></div>
		<div class='row ribbon-vert-stitches-bottom'></div>
	</div>
	<div class='container-fluid listing'>
	<%= render 'form' %>
	</div>
	</br>
	</br>
</body>

	